In [ ]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.7.13
NumPy 1.21.6


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

## **1. *FizzBuzz*  - Python**

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzz(3)

#  --> Expected output: Fizz!

FizzBuzz(11)

#  --> Expected output: ...

FizzBuzz(5)
#  --> Expected output: Buzz!

FizzBuzz(7)
#  --> Expected output:...

FizzBuzz(15)
#  --> Expected output: FizzBuzz!
```

---

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):

    answer =""

    if(x%3 == 0 and x%5!=0):
      answer="Fizz!"
    
    elif(x%5==0 and x%3!=0):
      answer = "Buzz!"
    elif(x%5==0 and x%3==0):
      answer = "FizzBuzz!"
    else:
      answer = "..."


    return answer




<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [ ]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzzList(4)
#  --> Expected output: ['...', '...', 'Fizz!', '...']
 
FizzBuzzList(-1)
#  --> Expected output: []
```
---

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):

    ans = [] 

    for i in range(1,n+1):
      ans.append(FizzBuzz(i))

    return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [ ]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** functions ***`mean`*** and ***`std`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [ ]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


**Sample testcases**

```python
#run this sample testcases to help you validate your solution

X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
standarize(X0)

#  --> Expected output: array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

X1 = np.arange(5)
standarize(X1)

#  --> Expected output: array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

```
---

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X - np.mean(X)) / np.std(X)# only one line of code
  return X_standarized

## **4. *Main diagonal matrix*  - NumPy**

In [ ]:
t = [array([], dtype=float64), array([nan]), array([-1.,  1.]), array([-1.22474487,  0.        ,  1.22474487]), array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079]), array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356]), array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011]), array([-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5]), array([-1.52752523, -1.09108945, -0.65465367, -0.21821789,  0.21821789,
        0.65465367,  1.09108945,  1.52752523]), array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])]

In [ ]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


**Sample testcases**

```python
#run this sample testcases to help you validate your solution

A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])
```
---

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)# only one line of code
  return D

**¡Congratulations!** You have finished your first quiz.

