# **Test 1 NM 2023 I UNCode Programming Assignment**




#**|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||**#

#**1. Modify the given optimized code for PLU factorization to generate the sequence of transfromations from $A$,$U_1$,$U_2$,$\cdots$,$U_{n-2}$ to the uppper tiangular matrix $U$** 







In [42]:
import numpy as np

def diy_lu_optimized_sequences(a):
    n = len(a)
    secuencia_U = [np.copy(a)]  # Inicializar la secuencia U con la matriz original
    secuencia_P = []  # Inicializar la secuencia P como una lista vacía

    for k in range(n-1):
        max_val = np.abs(secuencia_U[k][k, k])
        max_fila = k
        for i in range(k+1, n):
            if np.abs(secuencia_U[k][i, k]) > max_val:
                max_val = np.abs(secuencia_U[k][i, k])
                max_fila = i
        
        if max_fila != k:
            # Intercambiar las filas k y max_fila en secuencia_U[k]
            secuencia_U[k][[k, max_fila], :] = secuencia_U[k][[max_fila, k], :]
            
            # Registrar los intercambios de filas en secuencia_P
            secuencia_P.append((k, max_fila))
        
        for i in range(k+1, n):
            factor = secuencia_U[k][i, k] / secuencia_U[k][k, k]
            secuencia_U[k][i, k] = factor  # Almacenar el factor en la parte inferior de U
            secuencia_U[k][i, k+1:] -= factor * secuencia_U[k][k, k+1:]
    
    return secuencia_U, secuencia_P

$$ \Lambda_1 P_1 A  = U_1 $$  
$$ \Lambda_2 P_2 U_1  = U_2$$
$$\vdots$$
$$\Lambda_{n-1} P_{n-1} U_{n-2} = U$$

---

###**Problem Description**


**Task:** Given a square matrix $A$ generate the sequence of transformations from $A$,$U_1$,$U_2$,$\cdots$,$U_{n-2}$ to the uppper tiangular matrix $U$ and the sequence of row swaps performed.

---

**Input Format:** the square matrix $A$ is a numpy square matrix.

**Output Format:** A tuple of the sequence of transformations [$A$,$U_1$,$U_2$,$\cdots$,$U_{n-2}$,$U$] is a list of numpy matrices with its elements rounded to $3$ decimal places and  the sequence of row swaps is a list of sorted tuples of the indices of the rows swapped.

---







**Sample testcases**

```python
#run this sample textcases on a cell to help you validate your solution

A = np.array([[4,3,1], [5,7,0], [9,9,3]])

diy_lu_optimized_sequences(A)

#  --> Expected output: ([array([[4., 3., 1.],
         [5., 7., 0.],
         [9., 9., 3.]]),
  array([[ 9.   ,  3.   ,  1.   ],
         [ 0.   ,  5.333, -0.556],
         [ 0.   ,  7.667,  2.556]]),
  array([[ 9.   ,  3.   ,  1.   ],
         [ 0.   ,  7.667, -0.556],
         [ 0.   ,  0.   ,  2.942]])],
 [(0, 2), (1, 2)])

A = np.array([[1,2,3,4], [2,3,4,5], [0,1,2,3],[6,7,8,9]])

diy_lu_optimized_sequences(A)

#  --> Expected output: ([array([[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [0., 1., 2., 3.],
         [6., 7., 8., 9.]]),
  array([[6.   , 2.   , 3.   , 4.   ],
         [0.   , 2.333, 3.   , 3.667],
         [0.   , 1.   , 2.   , 3.   ],
         [0.   , 6.667, 7.5  , 8.333]]),
  array([[6.   , 2.   , 3.   , 4.   ],
         [0.   , 6.667, 3.   , 3.667],
         [0.   , 0.   , 1.55 , 2.45 ],
         [0.   , 0.   , 6.45 , 7.05 ]]),
  array([[6.   , 2.   , 3.   , 4.   ],
         [0.   , 6.667, 3.   , 3.667],
         [0.   , 0.   , 6.45 , 2.45 ],
         [0.   , 0.   , 0.   , 6.461]])],
 [(0, 3), (1, 3), (2, 3)])
```

---

**Solution**

In [67]:
import math

def Taylor_e_to_x_nterm_plus_one_less_epsilon(x, epsilon):
    if x > 0:
        n = 0
        e_to_x = 0
        term = 1

        while abs(term) >= epsilon:
            e_to_x += term
            term *= x / (n + 1)
            n += 1

        return n, e_to_x

    elif x <= 0:
        n = 0
        e_to_minus_x = 0
        term = 1

        while abs(term) >= epsilon:
            e_to_minus_x += term
            term *= -x / (n + 1)
            n += 1

        e_to_x = 1 / e_to_minus_x

        return n, e_to_x

In [68]:
Taylor_e_to_x_nterm_plus_one_less_epsilon(x=-700,epsilon=10**(-19))


(1942, 9.859676543759759e-305)